version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend             # путь к Dockerfile backend
    env_file: ../.env
    depends_on: [db]
    volumes:
      - media_data:${MEDIA_ROOT}      # расшарим папку с файлами
    expose: ["8000"]                  # для nginx внутри сети

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - media_data:${MEDIA_ROOT}:ro
      - ../backend/static:/static:ro  # билд фронта, собранный WhiteNoise‑ом
    ports:
      - "80:80"
      - "443:443"
    depends_on: [backend]

volumes:
  db_data:
  media_data:
