name: CI

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:                          # поднимаем Postgres для тестов
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      # ---------- Backend tests ----------
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: core.settings
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_HOST: localhost
        run: |
          cd backend
          python manage.py migrate --noinput
          python manage.py test

      # ---------- Build Docker images ----------
      - name: Build images
        run: docker-compose -f infra/docker-compose.yml build --parallel
